"""Doc link integrity check (F-001-U-5).

Walks every `.md` file in the repo and asserts every Markdown link is
resolvable:

  * Relative paths point at files that exist.
  * Same-file `#anchor` references match a heading in that file.
  * Cross-file `path#anchor` references match a heading in the target
    file.
  * `http(s)://...` links are NOT fetched (would flake in CI / network-
    free sandboxes); only their syntactic shape is validated.

This catches the most common dead-link failure modes — renamed files
not chased through cross-references, deleted sections still linked
from elsewhere, anchor typos — without introducing a flaky network
dependency. A repo-internal linkcheck is what U-5's "tests" section
calls for.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent

# Markdown link syntax `[text](target)`. The `target` capture stops at
# the first space (the title syntax `[text](url "title")` is rare here)
# or at the closing paren. We accept a wide set of inner-text characters
# because some of our docs include nested brackets in code spans inside
# the text portion.
LINK_RE = re.compile(r"\[(?:[^\]]+)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")

# Markdown ATX heading. We support up to six `#`'s; the content is what
# GitHub renders, which we then slugify with `_slugify`.
HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$", re.MULTILINE)


def _markdown_files() -> list[Path]:
    """Every tracked .md file under the repo root, sorted for stable test ids."""
    out: list[Path] = []
    for p in REPO_ROOT.rglob("*.md"):
        # Skip anything inside the venv / build artefacts. `.venv` is the
        # convention this repo's CONTRIBUTING.md endorses; CI runs from a
        # fresh checkout and won't have these, but local devs will.
        # `.pytest_cache` is generated by pytest itself; its README links
        # at the pytest project URL, not at our repo.
        parts = p.relative_to(REPO_ROOT).parts
        skip_top = {
            ".venv",
            "build",
            "dist",
            "snapshots",
            ".git",
            ".pytest_cache",
            ".mypy_cache",
            ".ruff_cache",
            "__pycache__",
            ".coverage",
        }
        if parts and parts[0] in skip_top:
            continue
        # Also skip vendored fixtures whose link semantics aren't ours.
        if "site-packages" in parts:
            continue
        out.append(p)
    out.sort()
    return out


def _slugify(heading_text: str) -> str:
    """GitHub's heading-to-anchor slug rules (close enough).

    Lowercase, replace whitespace runs with `-`, strip everything except
    `[a-z0-9-_]`. GitHub's exact algorithm is documented here:
      https://docs.github.com/en/get-started/writing-on-github

    Edge cases we deliberately handle:
      * Inline code spans (`code`) — drop the backticks but keep content.
      * Multiple `#` headings with the same text — GitHub appends `-1`,
        `-2`, ...; we recognize both forms (caller checks the base slug,
        then any `<base>-<n>` form).
      * Punctuation like `+`, `/`, `.` are dropped (so "design goals +
        non-goals" → "design-goals--non-goals", with the double-dash
        preserved verbatim — that matches the existing ARCHITECTURE.md
        ToC entries).
    """
    text = heading_text.strip()
    # Strip inline code backticks but keep content.
    text = text.replace("`", "")
    text = text.lower()
    # Convert whitespace runs to single hyphens BEFORE stripping
    # punctuation, so "design + goals" produces consistent multi-hyphen
    # output that matches what GitHub renders.
    text = re.sub(r"\s+", "-", text)
    # Now drop anything that isn't allowed.
    text = re.sub(r"[^a-z0-9_\-]", "", text)
    return text


def _headings(md_path: Path) -> set[str]:
    """All heading slugs in `md_path`, plus their `-1`, `-2`, ... duplicates.

    GitHub disambiguates duplicate heading slugs by appending `-N` (1-
    indexed, starting at the second occurrence). We pre-compute every
    such slug into the set so the link check can use plain `in` lookups.
    """
    text = md_path.read_text(encoding="utf-8")
    counts: dict[str, int] = {}
    slugs: set[str] = set()
    for match in HEADING_RE.finditer(text):
        slug = _slugify(match.group(2))
        if not slug:
            continue
        if slug not in counts:
            counts[slug] = 0
            slugs.add(slug)
        else:
            counts[slug] += 1
            slugs.add(f"{slug}-{counts[slug]}")
    return slugs


def _resolve_relative(target: str, source: Path) -> Path:
    """Resolve a relative link target against the directory of `source`."""
    return (source.parent / target).resolve()


def _is_external(target: str) -> bool:
    """True for http(s) and mailto links; those we don't validate."""
    return target.startswith(("http://", "https://", "mailto:", "tel:"))


def _classify(target: str) -> str:
    """Classify a link target for routing in the test below."""
    if _is_external(target):
        return "external"
    if target.startswith("#"):
        return "same_file_anchor"
    if "#" in target:
        return "cross_file_anchor"
    return "relative_file"


@pytest.mark.parametrize("md_path", _markdown_files(), ids=lambda p: str(p.relative_to(REPO_ROOT)))
def test_markdown_links_resolve(md_path: Path) -> None:
    """Every relative link + anchor in every .md file is reachable."""
    text = md_path.read_text(encoding="utf-8")

    # Pre-compute headings for THIS file (used for same-file anchors).
    own_headings = _headings(md_path)

    failures: list[str] = []
    for match in LINK_RE.finditer(text):
        target = match.group(1).strip()
        # Skip Markdown reference-style links `[text][ref]`; we only
        # match `[text](target)` above so they don't show up here.
        if not target:
            continue
        kind = _classify(target)
        if kind == "external":
            # We don't fetch URLs. As a soft sanity check, every
            # external link must at least have a non-empty host segment.
            if "://" in target and not target.split("://", 1)[1]:
                failures.append(f"empty host in {target!r}")
            continue
        if kind == "same_file_anchor":
            anchor = target.lstrip("#")
            if anchor not in own_headings:
                failures.append(
                    f"same-file anchor {target!r} doesn't match any heading in "
                    f"{md_path.relative_to(REPO_ROOT)}"
                )
            continue
        if kind == "cross_file_anchor":
            path_part, anchor = target.split("#", 1)
            resolved = _resolve_relative(path_part, md_path)
            if not resolved.exists():
                failures.append(f"cross-file link target missing: {target!r} → {resolved}")
                continue
            if resolved.suffix.lower() != ".md":
                # Anchors only make sense for markdown files. Tolerate.
                continue
            cross_headings = _headings(resolved)
            if anchor not in cross_headings:
                failures.append(
                    f"cross-file anchor missing: {target!r} (in {md_path.relative_to(REPO_ROOT)})"
                )
            continue
        # Plain relative file reference.
        resolved = _resolve_relative(target, md_path)
        if not resolved.exists():
            failures.append(
                f"relative link target missing: {target!r} → {resolved} "
                f"(in {md_path.relative_to(REPO_ROOT)})"
            )

    assert not failures, (
        f"{len(failures)} broken link(s) in {md_path.relative_to(REPO_ROOT)}:\n"
        + "\n".join(f"  - {f}" for f in failures)
    )


def test_linkcheck_has_files() -> None:
    """Guardrail: if `_markdown_files()` ever returns empty, the parametrize
    decorator above silently passes — which would let real dead links slip
    in. Assert there's at least one .md file in scope so a future repo
    reorganization can't silently skip the check.
    """
    files = _markdown_files()
    assert len(files) >= 5, files
    # And the most-load-bearing docs are in scope.
    rel = {str(f.relative_to(REPO_ROOT)) for f in files}
    assert "README.md" in rel
    assert "BACKLOG.md" in rel
    assert "docs/ARCHITECTURE.md" in rel
    assert "docs/PROPOSAL-docker-workers.md" in rel
